name: Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          response = $(curl --location '${{ vars.BASE_URL }}scoreboard' --header ${{ secrets.TOKEN }})
          echo "${{fromJson(response).rows}}"
