name: POST submission

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

env:
  FN_PROB: "problems.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.prob.outputs.ids }}
    steps:
      - uses: actions/checkout@v4
      - run: make
      - id: prob
        run: |
          make problems PROBLEMS=${{ env.FN_PROB }}
          echo "ids=$(cat ${{ env.FN_PROB }})" >> $GITHUB_OUTPUT
      - run: echo "${{ steps.prob.outputs.ids }}"
  submit:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pid: ${{ steps.prob.outputs.ids }}  # run once for each known problem id
    steps:
      - id: content
        run: echo "body=$(cat build/${{ matrix.pid }}.txt)" >> $GITHUB_OUTPUT
      - name: post solution
        run: |
          echo "${{ matrix.pid }}"
          echo "${{ steps.content.outputs.body }}"
#          curl --location '${{ vars.BASE_URL }}submission' \
#          --header ${{ secrets.TOKEN }} \
#          --header 'Content-Type: text/plain' \
#          --data '${{ steps.content.outputs.body }}'

