name: POST submission

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

env:
  FN_PROB: "problems.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make
      - id: prob
        run: |
          make problems PROBLEMS=${{ env.FN_PROB }}
          echo "ids=$(cat ${{ env.FN_PROB }})" >> $GITHUB_OUTPUT

#  submit:
#    runs-on: ubuntu-latest
#    needs: build
#    strategy:
#      matrix:
#        pid: ${{ steps.prob.outputs.ids }}  # for each problem id
#    steps:
#      - name: read solution
#        id: content
#        run: echo "body=$(cat build/${{ matrix.pid }}.txt)" >> $GITHUB_OUTPUT
#      - name: post solution
#        run: |
#          # problem id and submission content
#          echo "${{ matrix.pid }}"
#          echo "${{ steps.content.outputs.body }}"
#          curl --location '${{ vars.BASE_URL }}submission' \
#          --header ${{ secrets.TOKEN }} \
#          --header 'Content-Type: text/plain' \
#          --data '${{ steps.content.outputs.body }}'

